        db      88h
        db      28h
        db      81h
        db      10h
        db      08h
        db      0E1h
        db      30h
        db      05h
        db      0FFh
        db      24h
        db      27h
        db      2Ah
        db      31h
        db      2Ch
        db      2Ah
        db      0FFh
        db      8Ch
        db      2Ch
        db      61h
        db      50h
        db      0FFh
        db      2Dh
        db      21h
        db      25h
        db      2Ch
        db      2Ah
        db      28h
        db      0FFh
        db      0E7h
        db      50h
        db      4Ah
        db      4Ch
        db      31h
        db      0F4h
        db      0Ah
        db      08h
        db      07h
        db      88h
        db      07h
        db      08h
        db      0E5h
        db      30h
        db      0Fh
        db      0FFh
        db      2Dh
        db      21h
        db      25h
        db      2Ah
        db      31h
        db      35h
        db      0FFh
        db      9Ch
        db      1Ah
        db      18h
        db      0F7h
        db      14h
        db      15h
        db      17h
        db      74h
        db      50h
        db      0Ch
        db      97h
        db      15h
        db      0Ch
        db      97h
        db      15h
        db      0Ch
        db      51h
        db      5Ch
        db      3Ah
        db      74h
        db      50h
        db      0Ch
        db      77h
        db      75h
        db      8Ch
        db      30h
        db      2Ah
        db      2Ch
        db      31h
        db      35h
        db      94h
        db      10h
        db      0Ch
        db      4Ah
        db      4Ch
        db      31h
        db      54h
        db      55h
        db      37h
        db      58h
        db      57h
        db      35h
        db      91h
        db      10h
        db      0Ch
        db      0EAh
        db      0Ch
        db      11h
        db      13h
        db      95h
        db      30h
        db      54h
        db      55h
        db      36h
        db      97h
        db      20h
END
