
        db      91h
        db      9Ch
        db      7Ah
        db      0D4h
        db      80h
        db      2Ch
        db      0B7h
        db      0B5h
        db      0CCh
        db      60h
        db      6Ah
        db      6Ch
        db      71h
        db      75h
        db      0D4h
        db      20h
        db      2Ch
        db      8Ah
        db      8Ch
        db      71h
        db      94h
        db      95h
        db      77h
        db      98h
        db      97h
        db      75h
        db      0D1h
        db      20h
        db      2Ch
        db      0AAh
        db      2Ah
        db      2Ch
        db      31h
        db      33h
        db      0D5h
        db      60h
        db      94h
        db      95h
        db      76h
        db      0D7h
        db      60h
end
